"""AUTOGENERATED SPLIT — see rr_test/server/server.py for history."""
from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import time
import threading
from datetime import datetime
from typing import Any, Optional, Set

from rr_test.vehicle.connection import UUT
from rr_test.vehicle.constants import TestMode, UUTStatus, AlertSeverity
from rr_test.hardware.daq import SimpleDAQController
from rr_test.execution import UUTTestExecutor, PlaybackTestExecutor
from rr_test.execution.callbacks import ExecutorCallbacks

_log = logging.getLogger(__name__)

_HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class AppState:
    """Central mutable state shared between the WS server and test executors."""

    def __init__(self) -> None:
        self.uuts: list[UUT] = []
        self.daq: SimpleDAQController = SimpleDAQController()
        self.testing_active: bool = False
        self.test_mode: str = "ibit"
        self.current_test_executor: Optional[Any] = None
        self.current_uut_index: int = -1
        self.batch_start_datetime: Optional[datetime] = None
        self.batch_end_time: Optional[float] = None
        self._starting_uut: bool = False

        # Playback-mode specific params (set by _start_test from the cmd payload)
        self.playback_csv: str = ""
        self.playback_type: str = "Both"

        # Vehicle / telemetry state (updated by executor callbacks)
        self.vehicle_mode: int = 0
        self.vehicle_regime: int = 0
        self.vehicle_armed: bool = False
        self.vehicle_relay_on: bool = False
        self.connection_healthy: bool = False
        self.ibit_substate: str = "IDLE"
        self.mistracking_flags: int = 0
        self.ibit_duration: float = 0.0
        self.actuator_data: dict = {}
        self.statistics: Optional[dict] = None
        self.iteration: int = 0

        # DAQ state
        self.daq_initialized: bool = False
        self.daq_device: Optional[str] = None
        self.daq_num_lines: int = 0
        self.daq_sitl_active: bool = False
        self.daq_devices: list[str] = []

        # Config
        self.test_config: dict = {
            "ibit_timeout": 300.0,
            "phase_timeout": 90.0,
            "arm_timeout": 60.0,
            "max_arm_iterations": 20,
            "skip_arm_for_ibit": False,
        }

        # Log directory
        self.project_root = _HERE
        self.log_directory = os.path.join(_HERE, "logs")
        self.report_directory = os.path.join(_HERE, "reports")
        os.makedirs(self.log_directory, exist_ok=True)
        os.makedirs(self.report_directory, exist_ok=True)

        # Load saved settings
        self._settings_path = os.path.join(_HERE, "app_settings.json")
        self.load_settings()

    def _validate_dir_path(self, path: str) -> str | None:
        """Return path if it's valid for the current platform, else None.

        Detects Windows-style absolute paths ('C:\\...') on non-Windows
        systems — those would be treated as a literal filename by os.makedirs
        and create a junk directory ('C:\\Anduril\\...') in the project root.
        """
        if not isinstance(path, str) or not path:
            return None
        # On Linux/macOS, reject Windows drive-letter paths
        if sys.platform != "win32":
            if len(path) >= 2 and path[1] == ":" and path[0].isalpha():
                return None
            if "\\" in path:  # backslash in a POSIX path is almost always wrong
                return None
        return path

    def load_settings(self) -> None:
        """Load settings from app_settings.json if it exists."""
        try:
            if os.path.isfile(self._settings_path):
                with open(self._settings_path, "r") as f:
                    data = json.load(f)
                if "log_directory" in data:
                    valid = self._validate_dir_path(data["log_directory"])
                    if valid:
                        self.log_directory = valid
                        os.makedirs(self.log_directory, exist_ok=True)
                    else:
                        _log.info(
                            "Ignoring incompatible log_directory '%s' — "
                            "using default %s",
                            data["log_directory"], self.log_directory,
                        )
                if "report_directory" in data:
                    valid = self._validate_dir_path(data["report_directory"])
                    if valid:
                        self.report_directory = valid
                        os.makedirs(self.report_directory, exist_ok=True)
                if "test_config" in data:
                    self.test_config.update(data["test_config"])
                if "test_mode" in data:
                    self.test_mode = data["test_mode"]
                for key in ("ibit_timeout", "phase_timeout", "arm_timeout", "max_arm_iterations"):
                    if key in data:
                        self.test_config[key] = data[key]
                if "skip_arm_for_ibit" in data:
                    self.test_config["skip_arm_for_ibit"] = data["skip_arm_for_ibit"]
                _log.info("Loaded settings from %s", self._settings_path)
        except Exception as e:
            _log.warning("Failed to load settings: %s", e)

    def save_settings(self) -> None:
        """Save current settings to app_settings.json."""
        try:
            data = {
                "log_directory": self.log_directory,
                "report_directory": self.report_directory,
                "test_config": self.test_config,
                "test_mode": self.test_mode,
                "connection_timeout": 10,
                "stabilization_delay": 2,
                "skip_state_management": False,
                "skip_arm_for_ibit": self.test_config.get("skip_arm_for_ibit", False),
                "ibit_timeout": self.test_config.get("ibit_timeout", 300),
                "phase_timeout": self.test_config.get("phase_timeout", 90),
                "arm_timeout": self.test_config.get("arm_timeout", 60),
                "max_arm_iterations": self.test_config.get("max_arm_iterations", 20),
                "playback_csv": "",
                "playback_type": "Both",
                "test_temperature_c": None,
            }
            with open(self._settings_path, "w") as f:
                json.dump(data, f, indent=2)
            _log.info("Saved settings to %s", self._settings_path)
        except Exception as e:
            _log.warning("Failed to save settings: %s", e)

    def to_sync_dict(self) -> dict:
        """Build the full state.sync payload for a newly connected client."""
        return {
            "uuts": [self._uut_dict(u) for u in self.uuts],
            "daq": {
                "initialized": self.daq_initialized,
                "device": self.daq_device,
                "num_lines": self.daq_num_lines,
                "sitl_active": self.daq_sitl_active,
                "devices": self.daq_devices,
            },
            "batch": self._batch_dict(),
            "vehicle": {
                "mode": self.vehicle_mode,
                "regime": self.vehicle_regime,
                "armed": self.vehicle_armed,
                "relay_on": self.vehicle_relay_on,
                "connection_healthy": self.connection_healthy,
            },
            "ibit": {
                "substate": self.ibit_substate,
                "mistracking_flags": self.mistracking_flags,
                "duration_seconds": self.ibit_duration,
            },
            "actuator": self.actuator_data,
            "statistics": self.statistics,
            "test_mode": self.test_mode,
            "config": self.test_config,
        }

    def _batch_dict(self) -> dict:
        elapsed = 0.0
        remaining = 0.0
        if self.testing_active and self.batch_end_time:
            now = time.monotonic()
            start_mono = getattr(self, "_batch_start_mono", now)
            elapsed = max(0.0, now - start_mono)
            remaining = max(0.0, self.batch_end_time - now)

        return {
            "active": self.testing_active,
            "mode": self.test_mode,
            "current_uut_index": self.current_uut_index,
            "current_uut_serial": (
                self.uuts[self.current_uut_index].serial_number
                if 0 <= self.current_uut_index < len(self.uuts)
                else None
            ),
            "elapsed_seconds": elapsed,
            "remaining_seconds": remaining,
            "total_uuts": len(self.uuts),
            "active_uuts": sum(
                1 for u in self.uuts if getattr(u, "status", "") != "Failed (3x)"
            ),
        }

    @staticmethod
    def _uut_dict(u: UUT) -> dict:
        # Map Python UUTStatus strings to frontend-expected values
        STATUS_MAP = {
            "Ready":       "READY",
            "Testing":     "TESTING",
            "Complete":    "PASSED",
            "Failed":      "FAILED",
            "Failed (3x)": "FAILED_PERMANENT",
            "Retry":       "RETRY",
            "Stopped":     "SKIPPED",
        }
        raw_status = u.status if isinstance(u.status, str) else str(u.status)
        normalized = STATUS_MAP.get(raw_status, raw_status.upper().replace(" ", "_").replace("(", "").replace(")", ""))
        return {
            "serial_number": u.serial_number,
            "ip_address": u.ip_address,
            "port": u.port,
            "relay_line": u.relay_line,
            "status": normalized,
            "iterations_completed": getattr(u, "iterations_completed", 0),
            "consecutive_failures": getattr(u, "consecutive_failures", 0),
            "soft_failures": getattr(u, "soft_failures", 0),
        }


# ═══════════════════════════════════════════════════════════════════════════════
# Broadcast manager — pushes events to all connected WebSocket clients
# ═══════════════════════════════════════════════════════════════════════════════

