"""AUTOGENERATED SPLIT — see rr_test/server/server.py for history."""
from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import time
import threading
from datetime import datetime
from typing import Any, Optional, Set

# from rr_test.vehicle.connection import UUT
# from rr_test.vehicle.constants import TestMode, UUTStatus, AlertSeverity
# from rr_test.hardware.daq import SimpleDAQController
# from rr_test.execution import UUTTestExecutor, PlaybackTestExecutor
# from rr_test.execution.callbacks import ExecutorCallbacks

_log = logging.getLogger(__name__)

_HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import websockets
from websockets.asyncio.server import ServerConnection

class Broadcaster:
    """Thread-safe broadcaster for WebSocket messages."""

    def __init__(self, loop: asyncio.AbstractEventLoop) -> None:
        self._clients: Set[ServerConnection] = set()
        self._loop = loop

    def register(self, ws: ServerConnection) -> None:
        self._clients.add(ws)

    def unregister(self, ws: ServerConnection) -> None:
        self._clients.discard(ws)

    def broadcast(self, msg_type: str, data: Any = None) -> None:
        """Send a message to all connected clients (thread-safe)."""
        payload = json.dumps({"type": msg_type, "data": data})
        if self._clients:
            asyncio.run_coroutine_threadsafe(
                self._broadcast_async(payload), self._loop
            )

    async def _broadcast_async(self, payload: str) -> None:
        dead: list[ServerConnection] = []
        for ws in self._clients:
            try:
                await ws.send(payload)
            except Exception:
                dead.append(ws)
        for ws in dead:
            self._clients.discard(ws)

    async def send_to(self, ws: ServerConnection, msg_type: str, data: Any = None) -> None:
        """Send a message to a specific client."""
        try:
            await ws.send(json.dumps({"type": msg_type, "data": data}))
        except Exception:
            pass


# ═══════════════════════════════════════════════════════════════════════════════
# Executor callback bridge (replaces QtExecutorBridge for the web UI)
# ═══════════════════════════════════════════════════════════════════════════════

