"""AUTOGENERATED SPLIT — see rr_test/server/server.py for history."""
from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import time
import threading
from datetime import datetime
from typing import Any, Optional, Set

from rr_test.vehicle.connection import UUT
from rr_test.vehicle.constants import TestMode, UUTStatus, AlertSeverity
from rr_test.hardware.daq import SimpleDAQController
from rr_test.execution import UUTTestExecutor, PlaybackTestExecutor
from rr_test.execution.callbacks import ExecutorCallbacks

_log = logging.getLogger(__name__)

_HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rr_test.server.app_state import AppState
from rr_test.server.broadcaster import Broadcaster

def wire_callbacks(state: AppState, broadcaster: Broadcaster) -> ExecutorCallbacks:
    """Create an ExecutorCallbacks that pushes events to WebSocket clients."""
    cb = ExecutorCallbacks()

    def _log(msg: str) -> None:
        ts = datetime.now().isoformat()
        broadcaster.broadcast("test.log", {"message": msg, "level": "info", "timestamp": ts})
        # Detect connection success from executor log messages and broadcast health
        if "\u2713 Connected to" in msg and not state.connection_healthy:
            state.connection_healthy = True
            broadcaster.broadcast("connection.health", {"healthy": True})

    def _complete(success: bool, message: str) -> None:
        # Per-UUT iteration complete — does NOT end the batch.
        # The batch loop in _run_batch continues until the duration expires,
        # all UUTs permanently fail, or the user clicks Stop.
        broadcaster.broadcast("uut.iteration_complete", {
            "success": success, "message": message,
        })
        broadcaster.broadcast("batch.status", state._batch_dict())

    def _mode(m: int) -> None:
        state.vehicle_mode = m
        broadcaster.broadcast("telemetry.vehicle_status", {
            "mode": m, "regime": state.vehicle_regime, "armed": state.vehicle_armed,
        })

    def _armed(armed: bool, regime: int) -> None:
        state.vehicle_armed = armed
        state.vehicle_regime = regime
        broadcaster.broadcast("telemetry.vehicle_status", {
            "mode": state.vehicle_mode, "regime": regime, "armed": armed,
        })

    def _ibit_state(s: str) -> None:
        state.ibit_substate = s
        broadcaster.broadcast("ibit.state", {"substate": s})

    def _actuator(d: dict) -> None:
        state.actuator_data = d
        broadcaster.broadcast("telemetry.actuator", d)

    def _connection_health(h: bool) -> None:
        state.connection_healthy = h
        broadcaster.broadcast("connection.health", {"healthy": h})

    def _relay(on: bool) -> None:
        state.vehicle_relay_on = on
        broadcaster.broadcast("daq.relay", {"on": on})

    def _mistracking(flags: int) -> None:
        state.mistracking_flags = flags
        broadcaster.broadcast("ibit.mistracking", {"flags": flags})

    def _statistics(s: Any) -> None:
        if hasattr(s, "__dict__"):
            d = {}
            for k, v in s.__dict__.items():
                if k.startswith('_'):
                    continue
                if callable(v):
                    continue
                # Convert deques to lists for JSON serialization
                if hasattr(v, '__iter__') and not isinstance(v, (str, dict, list)):
                    try:
                        d[k] = list(v)
                    except Exception:
                        continue
                else:
                    d[k] = v
            # Ensure the expected fields exist for the frontend
            d.setdefault("total_iterations", d.get("telemetry_received", 0))
            d.setdefault("total_passes", 0)
            d.setdefault("total_fails", 0)
            d.setdefault("pass_rate", 0.0)
            d.setdefault("avg_duration", 0.0)
            d.setdefault("per_uut", {})
            state.statistics = d
        elif isinstance(s, dict):
            state.statistics = s
        try:
            broadcaster.broadcast("test.statistics", state.statistics)
        except Exception:
            pass  # Non-serializable statistics — skip this broadcast

    def _duration(d: float) -> None:
        state.ibit_duration = d
        broadcaster.broadcast("test.duration", {"seconds": d})

    def _alert(msg: str) -> None:
        broadcaster.broadcast("alert", {"message": msg, "severity": "warning"})

    def _status(s: str) -> None:
        broadcaster.broadcast("test.status", {"status": s})

    def _iteration(i: int) -> None:
        state.iteration = i
        broadcaster.broadcast("test.iteration", {"iteration": i})
        # Also broadcast updated UUT list so iterations_completed is visible
        broadcaster.broadcast("uut.update", {
            "uuts": [state._uut_dict(u) for u in state.uuts],
        })

    def _progress(p: int) -> None:
        broadcaster.broadcast("test.progress", {"percent": p})

    cb.on_log = _log
    cb.on_complete = _complete
    cb.on_mode = _mode
    cb.on_armed_state = _armed
    cb.on_ibit_state = _ibit_state
    cb.on_actuator_feedback = _actuator
    cb.on_connection_health = _connection_health
    cb.on_relay_state = _relay
    cb.on_mistracking_update = _mistracking
    cb.on_statistics = _statistics
    cb.on_test_duration = _duration
    cb.on_alert = _alert
    cb.on_status = _status
    cb.on_iteration = _iteration
    cb.on_progress = _progress
    cb.on_time_expired = lambda: _complete(False, "Batch time expired")

    return cb


# ═══════════════════════════════════════════════════════════════════════════════
# Command handlers
# ═══════════════════════════════════════════════════════════════════════════════

