"""AUTOGENERATED SPLIT — see rr_test/server/server.py for history."""
from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import time
import threading
from datetime import datetime
from typing import Any, Optional, Set

from rr_test.vehicle.connection import UUT
from rr_test.vehicle.constants import TestMode, UUTStatus, AlertSeverity
from rr_test.hardware.daq import SimpleDAQController
from rr_test.execution import UUTTestExecutor, PlaybackTestExecutor
from rr_test.execution.callbacks import ExecutorCallbacks

_log = logging.getLogger(__name__)

_HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from websockets.asyncio.server import ServerConnection
from rr_test.server.app_state import AppState
from rr_test.server.broadcaster import Broadcaster
from rr_test.server.callbacks import wire_callbacks

class CommandHandler:
    """Processes commands received from the frontend."""

    def __init__(self, state: AppState, broadcaster: Broadcaster) -> None:
        self.state = state
        self.broadcaster = broadcaster

    async def handle(self, ws: ServerConnection, msg: dict) -> None:
        msg_type = msg.get("type", "")
        data = msg.get("data", {})

        handler_map = {
            "cmd.sync_state": self._sync_state,
            "cmd.detect_daq": self._detect_daq,
            "cmd.init_daq": self._init_daq,
            "cmd.launch_sitl": self._launch_sitl,
            "cmd.add_uut": self._add_uut,
            "cmd.edit_uut": self._edit_uut,
            "cmd.remove_uut": self._remove_uut,
            "cmd.start_test": self._start_test,
            "cmd.stop_test": self._stop_test,
            "cmd.emergency_stop": self._emergency_stop,
            "cmd.save_settings": self._save_settings,
            "cmd.save_uuts": self._save_uuts,
            "cmd.load_uuts": self._load_uuts,
            "cmd.upload_playback_csv": self._upload_playback_csv,
        }

        handler = handler_map.get(msg_type)
        if handler:
            await handler(ws, data)
        elif msg_type.startswith("cmd.debug."):
            await self._handle_debug(msg_type, data)
        else:
            await self.broadcaster.send_to(ws, "error", {"message": f"Unknown command: {msg_type}"})

    async def _sync_state(self, ws: ServerConnection, _data: dict) -> None:
        await self.broadcaster.send_to(ws, "state.sync", self.state.to_sync_dict())
        # Send a welcome log so the log panel isn't empty on first load
        await self.broadcaster.send_to(ws, "test.log", {
            "message": "Connected to Roadrunner Flight Test backend v5.0.0",
            "level": "info",
            "timestamp": datetime.now().isoformat(),
        })

    async def _detect_daq(self, _ws: ServerConnection, _data: dict) -> None:
        devices = SimpleDAQController.detect_devices()
        self.state.daq_devices = devices
        self.broadcaster.broadcast("daq.status", {
            "initialized": self.state.daq_initialized,
            "device": self.state.daq_device,
            "num_lines": self.state.daq_num_lines,
            "sitl_active": self.state.daq_sitl_active,
            "devices": devices,
        })
        if devices:
            self.broadcaster.broadcast("test.log", {
                "message": f"Found {len(devices)} DAQ device(s): {', '.join(devices)}",
                "level": "info",
                "timestamp": datetime.now().isoformat(),
            })

    async def _init_daq(self, _ws: ServerConnection, data: dict) -> None:
        device = data.get("device", "")
        if not device:
            return
        success, message = self.state.daq.initialize(device, num_lines=8)
        if success:
            self.state.daq_initialized = True
            self.state.daq_device = device
            self.state.daq_num_lines = self.state.daq.num_lines
        self.broadcaster.broadcast("daq.status", {
            "initialized": self.state.daq_initialized,
            "device": self.state.daq_device,
            "num_lines": self.state.daq_num_lines,
            "sitl_active": self.state.daq_sitl_active,
            "devices": self.state.daq_devices,
        })
        self.broadcaster.broadcast("test.log", {
            "message": f"{'DAQ initialized: ' + message if success else 'DAQ failed: ' + message}",
            "level": "info" if success else "error",
            "timestamp": datetime.now().isoformat(),
        })

    async def _launch_sitl(self, _ws: ServerConnection, _data: dict) -> None:
        """Launch SITL simulation in a background thread."""
        def _bg() -> None:
            import time as _time
            from rr_test.sim.vehicle import PandionVehicleSim
            from rr_test.sim.mock_daq import MockDAQController

            self.broadcaster.broadcast("test.log", {
                "message": "LAUNCHING SITL SIMULATION",
                "level": "info",
                "timestamp": datetime.now().isoformat(),
            })

            # Enable SITL mode (loopback + udpout) for connect_to_vehicle.
            # This is the ONLY hook the test system needs — no monkey-patching.
            os.environ["RR_SITL_MODE"] = "1"

            sim_configs = [
                {"serial": "RR-SIM-001", "port": 19901, "relay": 0,
                 "ibit_pass": True, "sysid": 1},
                {"serial": "RR-SIM-002", "port": 19902, "relay": 1,
                 "ibit_pass": False, "mistracking_flags": 0xC0, "sysid": 2},
            ]

            sims = []
            for cfg in sim_configs:
                sim = PandionVehicleSim(
                    vehicle_port=cfg["port"],
                    sysid=cfg["sysid"],
                    ibit_pass=cfg["ibit_pass"],
                    mistracking_flags=cfg.get("mistracking_flags", 0),
                    boot_time_s=2.0,
                    ibit_duration_scale=0.5,
                    boot_monitors=[0, 1, 2, 3],
                )
                threading.Thread(target=sim.start, daemon=True,
                                 name=f"sitl-{cfg['port']}").start()
                sims.append(sim)

            _time.sleep(2.5)

            mock_daq = MockDAQController()
            mock_daq.initialize("SimDAQ/SITL")
            for i, cfg in enumerate(sim_configs):
                mock_daq.register_vehicle(cfg["relay"], sims[i])

            self.state.daq = mock_daq
            self.state.daq_initialized = True
            self.state.daq_device = "SimDAQ/SITL"
            self.state.daq_sitl_active = True

            # Pre-load UUTs
            self.state.uuts = []
            for cfg in sim_configs:
                self.state.uuts.append(
                    UUT(cfg["serial"], "127.0.0.1", cfg["port"], cfg["relay"])
                )

            self.broadcaster.broadcast("daq.status", {
                "initialized": True,
                "device": "SimDAQ/SITL",
                "num_lines": 8,
                "sitl_active": True,
                "devices": ["SimDAQ/SITL"],
            })
            self.broadcaster.broadcast("uut.update", {
                "uuts": [self.state._uut_dict(u) for u in self.state.uuts],
            })
            self.broadcaster.broadcast("test.log", {
                "message": "SITL ready — click Start to test (RR-SIM-001: PASS, RR-SIM-002: FAIL)",
                "level": "info",
                "timestamp": datetime.now().isoformat(),
            })

        threading.Thread(target=_bg, daemon=True, name="sitl-launcher").start()

    async def _add_uut(self, _ws: ServerConnection, data: dict) -> None:
        uut = UUT(
            data.get("serial_number", ""),
            data.get("ip_address", ""),
            data.get("port", 0),
            data.get("relay_line", 0),
        )
        self.state.uuts.append(uut)
        self.broadcaster.broadcast("uut.update", {
            "uuts": [self.state._uut_dict(u) for u in self.state.uuts],
        })

    async def _edit_uut(self, _ws: ServerConnection, data: dict) -> None:
        idx = data.get("index", -1)
        if 0 <= idx < len(self.state.uuts):
            self.state.uuts[idx] = UUT(
                data.get("serial_number", ""),
                data.get("ip_address", ""),
                data.get("port", 0),
                data.get("relay_line", 0),
            )
            self.broadcaster.broadcast("uut.update", {
                "uuts": [self.state._uut_dict(u) for u in self.state.uuts],
            })

    async def _remove_uut(self, _ws: ServerConnection, data: dict) -> None:
        idx = data.get("index", -1)
        if 0 <= idx < len(self.state.uuts):
            self.state.uuts.pop(idx)
            self.broadcaster.broadcast("uut.update", {
                "uuts": [self.state._uut_dict(u) for u in self.state.uuts],
            })

    async def _start_test(self, _ws: ServerConnection, data: dict) -> None:
        if self.state.testing_active:
            return
        if not self.state.daq_initialized and not self.state.daq_sitl_active:
            self.broadcaster.broadcast("error", {"message": "DAQ not initialized"})
            return
        if not self.state.uuts:
            self.broadcaster.broadcast("error", {"message": "No UUTs configured"})
            return

        duration = data.get("duration_seconds", 86400)
        mode = data.get("mode", "ibit")
        self.state.test_mode = mode
        self.state.testing_active = True
        self.state.batch_start_datetime = datetime.now()
        self.state.batch_end_time = time.monotonic() + duration
        self.state._batch_start_mono = time.monotonic()
        self.state.current_uut_index = -1

        # Playback-mode specific parameters (ignored for IBIT).
        # If the client doesn't send playback_csv, keep whatever was set
        # by a prior cmd.upload_playback_csv so uploaded profiles aren't
        # silently wiped out.
        if "playback_csv" in data and data["playback_csv"]:
            self.state.playback_csv = data["playback_csv"]
        if "playback_type" in data and data["playback_type"]:
            self.state.playback_type = data["playback_type"]

        # Playback mode without a CSV is unrecoverable — tell the user
        # NOW instead of letting the executor fail mid-preparation.
        if mode == "playback" and not self.state.playback_csv:
            self.broadcaster.broadcast("error", {
                "message": (
                    "Cannot start Playback test: no flight profile CSV loaded. "
                    "Click the folder icon in Test Configuration to upload one."
                ),
            })
            self.state.testing_active = False
            self.broadcaster.broadcast("batch.status", self.state._batch_dict())
            return

        # Apply config overrides from frontend
        if "config" in data and isinstance(data["config"], dict):
            self.state.test_config.update(data["config"])

        # Auto-save settings on test start
        self.state.save_settings()

        # Reset UUTs
        for uut in self.state.uuts:
            uut.status = UUTStatus.READY
            uut.iterations_completed = 0
            uut.consecutive_failures = 0

        self.broadcaster.broadcast("batch.status", self.state._batch_dict())
        self.broadcaster.broadcast("uut.update", {
            "uuts": [self.state._uut_dict(u) for u in self.state.uuts],
        })
        self.broadcaster.broadcast("test.log", {
            "message": f"BATCH START — {mode.upper()} — Duration: {duration}s",
            "level": "info",
            "timestamp": datetime.now().isoformat(),
        })

        # Start test execution in a background thread
        threading.Thread(
            target=self._run_batch, daemon=True, name="batch-runner",
        ).start()

    def _run_batch(self) -> None:
        """Round-robin test execution loop (runs on a background thread)."""
        while self.state.testing_active:
            if time.monotonic() >= self.state.batch_end_time:
                self.broadcaster.broadcast("test.log", {
                    "message": "Batch time expired",
                    "level": "info",
                    "timestamp": datetime.now().isoformat(),
                })
                self.state.testing_active = False
                self.broadcaster.broadcast("test.complete", {
                    "success": True, "message": "Batch complete",
                })
                break

            # Check if all UUTs are permanently failed
            active = [u for u in self.state.uuts if getattr(u, 'status', '') != 'Failed (3x)']
            if not active:
                self.state.testing_active = False
                self.broadcaster.broadcast("test.complete", {
                    "success": False, "message": "All UUTs permanently failed",
                })
                break

            # Guard against empty UUT list
            if not self.state.uuts:
                time.sleep(0.5)
                continue

            # Round-robin to next UUT
            self.state.current_uut_index = (self.state.current_uut_index + 1) % len(self.state.uuts)
            uut = self.state.uuts[self.state.current_uut_index]

            if getattr(uut, 'status', '') == 'Failed (3x)':
                continue

            uut.status = UUTStatus.TESTING
            self.broadcaster.broadcast("uut.update", {
                "uuts": [self.state._uut_dict(u) for u in self.state.uuts],
            })
            self.broadcaster.broadcast("batch.status", self.state._batch_dict())

            # Reset per-UUT telemetry state so the frontend sees fresh data
            self.state.ibit_substate = "CONNECTING"
            self.state.mistracking_flags = 0
            self.state.ibit_duration = 0.0
            self.state.actuator_data = {}
            self.state.vehicle_mode = 0
            self.state.vehicle_regime = 0
            self.state.vehicle_armed = False
            self.state.vehicle_relay_on = False
            self.state.connection_healthy = False
            self.broadcaster.broadcast("ibit.state", {"substate": "CONNECTING"})
            self.broadcaster.broadcast("telemetry.vehicle_status", {
                "mode": 0, "regime": 0, "armed": False,
            })
            self.broadcaster.broadcast("connection.health", {"healthy": False})
            self.broadcaster.broadcast("telemetry.actuator", {})

            # Create callbacks
            callbacks = wire_callbacks(self.state, self.broadcaster)

            # Create and run executor
            if self.state.test_mode == "playback":
                executor = PlaybackTestExecutor(
                    uut, self.state.daq, self.state.batch_end_time,
                    stabilization_delay=2.0,
                    connection_timeout=10.0,
                    log_directory=self.state.log_directory,
                    test_start_datetime=self.state.batch_start_datetime,
                    playback_csv=self.state.playback_csv,
                    playback_type=self.state.playback_type,
                    config=self.state.test_config,
                    callbacks=callbacks,
                )
            else:
                executor = UUTTestExecutor(
                    uut, self.state.daq, self.state.batch_end_time,
                    stabilization_delay=2.0,
                    connection_timeout=10.0,
                    log_directory=self.state.log_directory,
                    test_start_datetime=self.state.batch_start_datetime,
                    config=self.state.test_config,
                    callbacks=callbacks,
                )

            self.state.current_test_executor = executor

            # Run synchronously on this thread (executor.run() blocks)
            try:
                executor.run()
            except Exception as e:
                _log.exception("Executor failed for %s", uut.serial_number)
                self.broadcaster.broadcast("test.log", {
                    "message": f"Executor error: {e}",
                    "level": "error",
                    "timestamp": datetime.now().isoformat(),
                })

            # Update UUT status and iteration count after executor completes
            self.broadcaster.broadcast("uut.update", {
                "uuts": [self.state._uut_dict(u) for u in self.state.uuts],
            })

        self.state.testing_active = False
        self.state.ibit_substate = "IDLE"
        self.broadcaster.broadcast("ibit.state", {"substate": "IDLE"})
        self.broadcaster.broadcast("batch.status", self.state._batch_dict())

    async def _stop_test(self, _ws: ServerConnection, _data: dict) -> None:
        self.state.testing_active = False
        if self.state.current_test_executor:
            try:
                self.state.current_test_executor.stop()
            except Exception:
                pass
        self.broadcaster.broadcast("test.log", {
            "message": "Test stopped by operator",
            "level": "warning",
            "timestamp": datetime.now().isoformat(),
        })
        self.broadcaster.broadcast("batch.status", self.state._batch_dict())

    async def _emergency_stop(self, _ws: ServerConnection, _data: dict) -> None:
        self.state.testing_active = False
        # Force all relays off
        try:
            self.state.daq.set_all_low()
        except Exception:
            pass
        if self.state.current_test_executor:
            try:
                self.state.current_test_executor.stop()
            except Exception:
                pass
        self.broadcaster.broadcast("test.log", {
            "message": "EMERGENCY STOP — All relays forced OFF",
            "level": "critical",
            "timestamp": datetime.now().isoformat(),
        })
        self.broadcaster.broadcast("alert", {
            "message": "EMERGENCY STOP activated — all relays OFF",
            "severity": "critical",
        })
        self.broadcaster.broadcast("batch.status", self.state._batch_dict())

    async def _save_settings(self, _ws: ServerConnection, _data: dict) -> None:
        self.state.save_settings()
        self.broadcaster.broadcast("test.log", {
            "message": "Settings saved",
            "level": "info",
            "timestamp": datetime.now().isoformat(),
        })

    async def _save_uuts(self, _ws: ServerConnection, data: dict) -> None:
        import json as _json
        path = data.get("path", "uut_config.json")
        try:
            uut_data = [self.state._uut_dict(u) for u in self.state.uuts]
            with open(path, "w") as f:
                _json.dump(uut_data, f, indent=2)
            self.broadcaster.broadcast("test.log", {
                "message": f"UUT config saved: {path}", "level": "info",
                "timestamp": datetime.now().isoformat(),
            })
        except Exception as e:
            self.broadcaster.broadcast("test.log", {
                "message": f"Failed to save UUTs: {e}", "level": "error",
                "timestamp": datetime.now().isoformat(),
            })

    async def _load_uuts(self, _ws: ServerConnection, data: dict) -> None:
        import json as _json
        path = data.get("path", "uut_config.json")
        try:
            with open(path) as f:
                uut_data = _json.load(f)
            self.state.uuts = [
                UUT(u["serial_number"], u["ip_address"], u["port"], u["relay_line"])
                for u in uut_data
            ]
            self.broadcaster.broadcast("uut.update", {
                "uuts": [self.state._uut_dict(u) for u in self.state.uuts],
            })
            self.broadcaster.broadcast("test.log", {
                "message": f"Loaded {len(self.state.uuts)} UUTs from {path}",
                "level": "info", "timestamp": datetime.now().isoformat(),
            })
        except Exception as e:
            self.broadcaster.broadcast("test.log", {
                "message": f"Failed to load UUTs: {e}", "level": "error",
                "timestamp": datetime.now().isoformat(),
            })

    async def _upload_playback_csv(
        self, _ws: ServerConnection, data: dict
    ) -> None:
        """Accept a flight profile CSV uploaded from the frontend file picker.

        The frontend reads the file locally and sends the text contents in
        the 'contents' field. We write it to logs/uploaded_<filename> so
        the Playback executor can open it by path. Broadcasts
        'playback.csv_uploaded' with the absolute path + frame count so
        the TestConfig UI can confirm success to the operator.
        """
        filename = (data.get("filename") or "upload.csv").strip()
        contents = data.get("contents", "")

        # Sanitize filename — use only the basename, no path separators.
        # (the browser sends the base name already, but we normalize in
        # case a malformed client sends something with separators).
        filename = os.path.basename(filename)
        if not filename:
            filename = "upload.csv"
        if not filename.lower().endswith(".csv"):
            filename = filename + ".csv"

        # Reject gigantic uploads to avoid disk-filling abuse. Real
        # Roadrunner flight profiles are 2-5 MB; cap at 50 MB.
        MAX_SIZE = 50 * 1024 * 1024
        if len(contents) > MAX_SIZE:
            self.broadcaster.broadcast("error", {
                "message": (
                    f"Uploaded CSV is too large "
                    f"({len(contents) / 1024 / 1024:.1f} MB > 50 MB max)"
                ),
            })
            return

        # Ensure target directory exists and write the file
        uploads_dir = os.path.join(self.state.log_directory, "uploaded")
        try:
            os.makedirs(uploads_dir, exist_ok=True)
            target_path = os.path.join(uploads_dir, filename)
            with open(target_path, "w", newline="") as f:
                f.write(contents)
        except Exception as e:
            self.broadcaster.broadcast("error", {
                "message": f"Failed to write uploaded CSV: {e}",
            })
            return

        # Count frames (non-header rows) so the UI can display progress-friendly info
        try:
            with open(target_path) as f:
                frame_count = max(0, sum(1 for _ in f) - 1)
        except Exception:
            frame_count = 0

        # Store on state so cmd.start_test picks it up even if the frontend
        # doesn't explicitly include playback_csv in the payload
        self.state.playback_csv = target_path

        self.broadcaster.broadcast("test.log", {
            "message": (
                f"✓ Flight profile uploaded: {filename} "
                f"({frame_count} frames) → {target_path}"
            ),
            "level": "info",
            "timestamp": datetime.now().isoformat(),
        })
        self.broadcaster.broadcast("playback.csv_uploaded", {
            "path": target_path,
            "filename": filename,
            "frames": frame_count,
        })

    async def _handle_debug(self, msg_type: str, data: dict) -> None:
        """Handle debug mode commands using a DebugConnection."""
        from rr_test.execution.debug_connection import DebugConnection
        from rr_test.vehicle.constants import MsgType, safe_int_field, is_armed
        from rr_test.execution.helpers import _build_actuator_feedback_dict

        ts = lambda: datetime.now().isoformat()

        # ── Connect / disconnect ─────────────────────────────────────────
        if msg_type == "cmd.debug.connect":
            serial = data.get("serial", "")
            ip = data.get("ip", "")
            port = data.get("port", 0)

            # Disconnect existing
            if hasattr(self.state, "_debug_conn") and self.state._debug_conn:
                self.state._debug_conn.disconnect()

            conn = DebugConnection(ip, port, serial)
            conn.on_log = lambda msg: self.broadcaster.broadcast(
                "test.log", {"message": msg, "level": "info", "timestamp": ts()})
            conn.on_error = lambda msg: self.broadcaster.broadcast(
                "test.log", {"message": msg, "level": "error", "timestamp": ts()})

            def _on_message(msg: object) -> None:
                msg_type_str = msg.get_type()
                try:
                    if msg_type_str == MsgType.ACTUATION_SYS_STATUS:
                        fb = _build_actuator_feedback_dict(msg)
                        self.state.actuator_data = fb
                        self.broadcaster.broadcast("telemetry.actuator", fb)
                        mode = safe_int_field(msg, "actuation_state")
                        self.state.vehicle_mode = mode
                        self.broadcaster.broadcast("telemetry.vehicle_status", {
                            "mode": mode,
                            "regime": self.state.vehicle_regime,
                            "armed": self.state.vehicle_armed,
                        })
                    elif msg_type_str == MsgType.PANDION_STATUS:
                        regime = safe_int_field(msg, "flight_regime", 255)
                        armed = is_armed(regime)
                        self.state.vehicle_regime = regime
                        self.state.vehicle_armed = armed
                        self.broadcaster.broadcast("telemetry.vehicle_status", {
                            "mode": self.state.vehicle_mode,
                            "regime": regime,
                            "armed": armed,
                        })
                    elif msg_type_str == "COMMAND_ACK":
                        cmd = getattr(msg, "command", 0)
                        result = getattr(msg, "result", -1)
                        result_names = {0: "ACCEPTED", 1: "TEMPORARILY_REJECTED",
                                        2: "DENIED", 3: "UNSUPPORTED", 4: "FAILED"}
                        self.broadcaster.broadcast("test.log", {
                            "message": f"ACK cmd={cmd}: {result_names.get(result, str(result))}",
                            "level": "info" if result == 0 else "error",
                            "timestamp": ts(),
                        })
                    elif msg_type_str == MsgType.BMS_DATA:
                        voltage = getattr(msg, 'pack_voltage_mV', 0) or 0
                        current = getattr(msg, 'pack_current_cA', 0) or 0
                        soc = getattr(msg, 'state_of_charge_percent', 0) or 0
                        self.broadcaster.broadcast("telemetry.battery", {
                            "voltage_mV": voltage,
                            "current_cA": current,
                            "soc": max(0, min(100, soc)),
                        })
                    elif msg_type_str == MsgType.ENGINE_STATUS:
                        self.broadcaster.broadcast("telemetry.engine", {
                            "rpm": getattr(msg, 'eng_1_speed', 0) or 0,
                            "egt_C": getattr(msg, 'eng_1_egt_temp_degC', 0) or 0,
                            "fuel_pump_mA": getattr(msg, 'eng_1_fuel_pump_curr_mA', 0) or 0,
                        })

                    # Add to debug message stream
                    summary = ""
                    for field in ("actuation_state", "flight_regime", "eng_1_speed", "text"):
                        val = getattr(msg, field, None)
                        if val is not None:
                            summary = str(val)[:30] if field == "text" else f"{field}={val}"
                            break
                    self.broadcaster.broadcast("debug.message", {
                        "msg_type": msg_type_str, "summary": summary,
                    })
                except Exception:
                    pass

            conn.on_message = _on_message

            def _on_connected(serial: str) -> None:
                self.state.connection_healthy = True
                self.broadcaster.broadcast("connection.health", {"healthy": True})

            def _on_disconnected(serial: str) -> None:
                self.state.connection_healthy = False
                self.broadcaster.broadcast("connection.health", {"healthy": False})

            conn.on_connected = _on_connected
            conn.on_disconnected = _on_disconnected

            self.state._debug_conn = conn
            threading.Thread(target=conn.connect, daemon=True, name="debug-connect").start()
            return

        if msg_type == "cmd.debug.disconnect":
            if hasattr(self.state, "_debug_conn") and self.state._debug_conn:
                threading.Thread(
                    target=self.state._debug_conn.disconnect, daemon=True
                ).start()
                self.state._debug_conn = None
            return

        # ── Commands requiring an active connection ──────────────────────
        conn = getattr(self.state, "_debug_conn", None)
        if not conn or not conn.master or not conn.master_lock:
            self.broadcaster.broadcast("test.log", {
                "message": "[DEBUG] No active connection",
                "level": "error",
                "timestamp": ts(),
            })
            return

        try:
            if msg_type == "cmd.debug.mode_request":
                mode_id = data.get("mode_id", 0)
                with conn.master_lock:
                    conn.master.mav.pandion_rr_actuation_request_mode_send(
                        requested_mode=mode_id
                    )
                self.broadcaster.broadcast("test.log", {
                    "message": f"-> Mode request: {mode_id}",
                    "level": "info",
                    "timestamp": ts(),
                })

            elif msg_type == "cmd.debug.arm":
                arm = data.get("arm", True)
                force = data.get("force", False)
                from pymavlink import mavutil
                param2 = 21196 if force and arm else 0
                with conn.master_lock:
                    conn.master.mav.command_long_send(
                        conn.master.target_system, 1,
                        mavutil.mavlink.MAV_CMD_COMPONENT_ARM_DISARM,
                        0, float(arm), float(param2), 0, 0, 0, 0, 0,
                    )
                label = ("Force ARM" if force else "ARM") if arm else "DISARM"
                self.broadcaster.broadcast("test.log", {
                    "message": f"-> {label} command sent",
                    "level": "info",
                    "timestamp": ts(),
                })

            elif msg_type == "cmd.debug.param_set":
                name = data.get("name", "")
                value = data.get("value", 0)
                from pymavlink import mavutil
                with conn.master_lock:
                    conn.master.mav.param_set_send(
                        conn.master.target_system, 1,
                        name.encode("utf-8"),
                        float(value),
                        mavutil.mavlink.MAV_PARAM_TYPE_UINT8,
                    )
                self.broadcaster.broadcast("test.log", {
                    "message": f"-> PARAM_SET {name} = {value}",
                    "level": "info",
                    "timestamp": ts(),
                })

            elif msg_type == "cmd.debug.monitor_override":
                cmd = data.get("cmd", 0)
                monitor_id = data.get("monitor_id", 0)
                cmd_names = {0: "CANCEL", 1: "SUPPRESS", 2: "FORCE_FAULT"}
                with conn.master_lock:
                    conn.master.mav.pandion_monitor_override_cmd_send(
                        override_cmd=cmd, monitor_id=monitor_id,
                    )
                self.broadcaster.broadcast("test.log", {
                    "message": f"-> Monitor {monitor_id}: {cmd_names.get(cmd, str(cmd))}",
                    "level": "info",
                    "timestamp": ts(),
                })

            elif msg_type == "cmd.debug.raw_command":
                cmd_id = data.get("cmd_id", 0)
                param1 = data.get("param1", 0.0)
                with conn.master_lock:
                    conn.master.mav.command_long_send(
                        conn.master.target_system, 1,
                        int(cmd_id), 0, param1, 0, 0, 0, 0, 0, 0,
                    )
                self.broadcaster.broadcast("test.log", {
                    "message": f"-> COMMAND_LONG cmd={cmd_id} p1={param1}",
                    "level": "info",
                    "timestamp": ts(),
                })

        except Exception as e:
            self.broadcaster.broadcast("test.log", {
                "message": f"[DEBUG] Command failed: {e}",
                "level": "error",
                "timestamp": ts(),
            })


# ═══════════════════════════════════════════════════════════════════════════════
# WebSocket server
# ═══════════════════════════════════════════════════════════════════════════════

